/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.graphics.personalizedComponents;

import boundary.graphics.Dialog;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 * Panel Personnalisé représentant un dé
 *
 * @author Robin MOUNIER
 */
public class Dice extends javax.swing.JPanel {

    private Dialog dialog;

    private int value = 1;
    private int nbAnimation = 0;
    private int storedValue = 0;
    private BufferedImage image1;
    private BufferedImage image2;
    private BufferedImage image3;
    private BufferedImage image4;
    private BufferedImage image5;
    private BufferedImage image6;
    private BufferedImage image7;
    private Timer timer = new Timer(50, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timerEventHandler(e);
            }
        });
    private Random random = new Random();

    /**
     * Creates new form Dice
     */
    public Dice() {
        initComponents();
        try{
            image1 = ImageIO.read(new File(getClass().getResource("/1.png").toURI()));
            image2 = ImageIO.read(new File(getClass().getResource("/2.png").toURI()));
            image3 = ImageIO.read(new File(getClass().getResource("/3.png").toURI()));
            image4 = ImageIO.read(new File(getClass().getResource("/4.png").toURI()));
            image5 = ImageIO.read(new File(getClass().getResource("/5.png").toURI()));
            image6 = ImageIO.read(new File(getClass().getResource("/6.png").toURI()));
            image7 = ImageIO.read(new File(getClass().getResource("/7.png").toURI()));

    }catch(Exception e){
        System.out.println(e);
    }
        repaint();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        switch(value){
            case 1:
                g.drawImage(image1, 0, 0, 100, 100, this);
                break;
            case 2:
                g.drawImage(image2, 0, 0, 100, 100, this);
                break;
            case 3:
                g.drawImage(image3, 0, 0, 100, 100, this);
                break;
            case 4:
                g.drawImage(image4, 0, 0, 100, 100, this);
                break;
            case 5:
                g.drawImage(image5, 0, 0, 100, 100, this);
                break;
            case 6:
                g.drawImage(image6, 0, 0, 100, 100, this);
                break;
            default:
                g.drawImage(image7, 0, 0, 100, 100, this);
        }

    }
    public void  setDiceValue(int v){
        value = v;
        storedValue = v;
        nbAnimation = 0;
        this.timer.start();
    }

    private void timerEventHandler(java.awt.event.ActionEvent e){
        if(nbAnimation < 30 + random.nextInt()%15){
            this.value = (random.nextInt()%7);
            nbAnimation++;
            repaint();
        }else{
            this.value = storedValue;
            timer.stop();
            repaint();
            dialog.diceFinished();
        }
    }

    public void setDialog(Dialog dialog) {
        this.dialog = dialog;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1542, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
