@startuml
hide footbox
title Diagramme de séquence - Méthode activateBox()

participant ActivateBox as "ActivateBoxControl"
participant PortalCase as "PortalCase"
participant Case as "Case"
participant Pirate as "Pirate"
participant IBoundary as "IBoundary"


-> ActivateBox : activateBox(listePirate, pirate, box)
activate ActivateBox
loop Pirate p : listePirate
    ActivateBox -> Pirate : getPosition()
    activate Pirate
    Pirate --> ActivateBox : position
    deactivate Pirate
end

ActivateBox -> PortalCase : effect(listePirate, pirate)
activate PortalCase
PortalCase -> Pirate : ajustPosition(5)
activate Pirate
Pirate --> PortalCase
deactivate Pirate
PortalCase -> Pirate : ajustHp(-3)
activate Pirate
Pirate --> PortalCase
deactivate Pirate
PortalCase -> Case : super() 
activate Case
    loop Pirate p : listePirates
    Case -> Pirate : getPosition()
    activate Pirate
    Pirate --> Case : position
    deactivate Pirate
    Case -> Pirate : getPosition()
    activate Pirate
    Pirate -> Case : postionPirate2
    deactivate Pirate
        alt !(p == pirate) && (position == postionPirate2)
            Case -> Pirate : ajustHP((Integer hp) -> hp-1)
            activate Pirate
            Pirate --> Case        
            deactivate Pirate    
        end
    end
Case --> PortalCase
deactivate Case

PortalCase --> ActivateBox
deactivate PortalCase

loop Pirate p : listePirates
    ActivateBox -> Pirate : getPosition()
    activate Pirate
    Pirate --> ActivateBox : position
    deactivate Pirate
    ActivateBox -> Pirate : getIdPirate()
    activate Pirate
    Pirate --> ActivateBox : id
    deactivate Pirate
    ActivateBox -> Pirate : getHp()
    activate Pirate
    Pirate --> ActivateBox : hp
    deactivate Pirate
    alt position != positionInitiale
        ActivateBox -> IBoundary : movePirateAuto(id, position)
        activate IBoundary
        IBoundary --> ActivateBox
        deactivate IBoundary
    end
    
    ActivateBox -> IBoundary : displayPV(id, hp)
    activate IBoundary
    IBoundary --> ActivateBox
    deactivate IBoundary
end

[<-- ActivateBox
deactivate ActivateBox
@enduml
