/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary.graphics;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author payrau
 */
public class Jack extends javax.swing.JPanel {
    private BufferedImage image;
private Image scaledImage;

    /**
     * Creates new form ImagePanel
     */
    public Jack() {
        initComponents();
        loadImage();
  
}
    private void loadImage(){
        
    try{
           image=ImageIO.read(new File("C:\\Users\\payra\\Desktop\\imagepirate\\tete2.jpg"));
           scaledImage= image.getScaledInstance(108, 108, Image.SCALE_SMOOTH);
        }catch(IOException e){
            throw new RuntimeException("Impossible de charger l'image",e);
           }
           
        }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        if(scaledImage != null){
            g.drawImage(scaledImage,0,0,this);
        }
    }
    
    @Override
    public Dimension getPreferredSize(){
        if(scaledImage!=null){
            return new Dimension(scaledImage.getWidth(this),scaledImage.getHeight(this));
        }
        return super.getPreferredSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
