/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package boundary;

/**
 *
 * @author corentin
 */
public class HealtBar extends javax.swing.JPanel {

    /**
     * Creates new form HealtBar
     */
    public HealtBar() {
        initComponents();
    }

    public void repaintCoeurs(int nbCoeur){
        switch (nbCoeur){
            case 5:
                jPanelCoeur5.repaintCoeur(true);
                jPanelCoeur4.repaintCoeur(true);
                jPanelCoeur3.repaintCoeur(true);
                jPanelCoeur2.repaintCoeur(true);
                jPanelCoeur1.repaintCoeur(true);
            case 4:
                jPanelCoeur5.repaintCoeur(false);
                jPanelCoeur4.repaintCoeur(true);
                jPanelCoeur3.repaintCoeur(true);
                jPanelCoeur2.repaintCoeur(true);
                jPanelCoeur1.repaintCoeur(true);
            case 3:
                jPanelCoeur5.repaintCoeur(false);
                jPanelCoeur4.repaintCoeur(false);
                jPanelCoeur3.repaintCoeur(true);
                jPanelCoeur2.repaintCoeur(true);
                jPanelCoeur1.repaintCoeur(true);
            case 2:
                jPanelCoeur5.repaintCoeur(false);
                jPanelCoeur4.repaintCoeur(false);
                jPanelCoeur3.repaintCoeur(false);
                jPanelCoeur2.repaintCoeur(true);
                jPanelCoeur1.repaintCoeur(true);
            case 1:
                jPanelCoeur5.repaintCoeur(false);
                jPanelCoeur4.repaintCoeur(false);
                jPanelCoeur3.repaintCoeur(false);
                jPanelCoeur2.repaintCoeur(false);
                jPanelCoeur1.repaintCoeur(true);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(5, 1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private PanelCoeur jPanelCoeur1;
private PanelCoeur jPanelCoeur2;
private PanelCoeur jPanelCoeur3;
private PanelCoeur jPanelCoeur4;
private PanelCoeur jPanelCoeur5;
}
